config/routes.rb
Rails.application.routes.draw do
  get 'hideposts/index'

  root to: 'welcome#home'

  get   'feed',                     to: 'posts#feed',       as: 'feed'
  get   '/login',                   to: 'sessions#bounce',  as: :login
  get   '/logout',                  to: 'sessions#destroy', as: :logout
  match '/auth/instagram/callback', to: 'sessions#create',  via: [:get]
  match '/auth/twitter/callback',   to: 'sessions#twitter', via: [:get]
  match '/auth/failure',            to: 'sessions#failure', via: [:get]

  resources :menu, only: [:index]
  resources :trips
  resources :travelings
  resources :hideposts
  resources :posts do
    resources :comments
  end

  get '/profile/:id', to: 'profiles#show', as: 'profile'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :posts, only: [:index, :show]
      resources :trips, only: [:index, :show] do
        resources :posts, only: [:index, :show]
      end
    end
  end

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  validates :title,      presence: true
  validates :start_date, presence: true
  validates :end_date,   presence: true

  has_many :travelings
  has_many :users, through: :travelings
  has_many :travels
  has_many :posts, through: :travels

  def format_start_date
    self.start_date.strftime("%b %d, %Y")
  end

  def format_end_date
    self.end_date.strftime("%b %d, %Y")
  end
end

app/controllers/api/v1/trips_controller.rb
class Api::V1::TripsController < Api::V1::ApiController
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @trips = current_user.trips.all
  end

  def new
    @trip = Trip.new
  end

  def edit
  end

  def update
    if @trip.update(trip_params)
      redirect_to @trip
    else
      render 'edit'
    end
  end

  def create
    @trip = current_user.trips.create(trip_params)

    if @trip.save
      # create a row in the travels table for each post within the selected dates
      start_date = params["trip"]["start_date"].to_datetime
      end_date   = params["trip"]["end_date"].to_datetime
      @trip.users.each do |user|
        user.posts.where.not(created_date: nil).each do |post|
          if post.created_date >= start_date && post.created_date <= end_date
            @trip.posts << post
            #@trip.save
            #Travel.create!(post_id: post.id, trip_id: @trip.id)
          end
        end
      end
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def show
    @posts   = @trip.posts.where(hide: false).order("created_date DESC")
    @users   = User.all
    @comment = Comment.new
  end

  def destroy
    if @trip.destroy
      redirect_to trips_path, notice: 'Trip was successfully deleted.'
    end
  end

  private

  def trip_params
    params.require(:trip).permit(:title, :start_date, :end_date, :user_id)
  end

  def set_trip
    @trip = Trip.find(params[:id])
  end
end

app/views/trips/edit.html.erb
<div class="full_background background_gray"></div>
<div class="title_container">
  <div class="menu_title">Create New Trip</div>
</div>
  <div class="new_trip_form">
    <%= form_for @trip do |f| %>

      <% if @trip.errors.any? %>
        <ul id="errors">
          <% @trip.errors.full_messages.each do |error| %>
            <li>
              <%= error %>
            </li>
          <% end %>
        </ul>
      <% end %>

      <div class="form">
        <%= f.text_field :title, class: "input_form", placeholder: "Name your trip"%>
      </div>
      <div class="form">
        <%= f.label :start_date, class: "label_form" %><br>
        <%= f.date_field :start_date, class: "input_form" %>
      </div>
      <div class="form">
        <%= f.label :end_date, class: "label_form" %><br>
        <%= f.date_field :end_date, class: "input_form" %>
      </div>
     <br/>
      <%= f.submit "Update Trip", class: "add_trip_btn" %>
    <% end %>
    <%= link_to "Cancel", trips_path, class:"cancel_btn" %>

  </div>

app/views/trips/index.html.erb
<%= link_to new_trip_path, class:"link_to" do %>
  <div class="trip_row">
    <div class="new_trip_background">
      <div class="new_trip_button">Create A Trip!</div>
    </div>
  </div>
<% end %>


<% if @trips.count != 0 %>
  <% @trips.reverse_each do |trip| %>
      <%= link_to trip, class:"link_to" do %>
        <div class="trip_row">
          <div class="index_trip_title"><%= trip.title %></div>
          <div class="index_trip_date"><%= trip.posts.count %> Posts in this trip</div>
          <div class="index_trip_date"><%= "From #{trip.start_date.to_date.strftime("%^b %e, %Y")} to #{trip.end_date.to_date.strftime("%^b %e, %Y")}" %></div>
          <%= link_to "edit", edit_trip_path(trip), class:"edit_btn" %>
          <%= link_to "delete", trip_path(trip), method: :delete, data: {confirm: "Are you sure?"}, class:"edit_btn" %>
        </div>
      <% end %>
  <% end %>
<% end %>

app/views/trips/new.html.erb
<div class="full_background background_gray"></div>
  <div class="title_container">
    <div class="menu_title">Create New Trip</div>
  </div>
    <div class="new_trip_form">
      <%= form_for @trip do |f| %>

        <% if @trip.errors.any? %>
          <ul id="errors">
            <% @trip.errors.full_messages.each do |error| %>
              <li>
                <%= error %>
              </li>
            <% end %>
          </ul>
        <% end %>

        <div class="form">
          <%= f.text_field :title, class: "input_form", placeholder: "Name your trip"%>
        </div>
        <div class="form">
          <%= f.label :start_date, class: "label_form" %><br>
          <%= f.date_field :start_date, class: "input_form" %>
        </div>
        <div class="form">
          <%= f.label :end_date, class: "label_form" %><br>
          <%= f.date_field :end_date, class: "input_form" %>
        </div>
       <br/>
        <%= f.submit "Create Trip", class: "add_trip_btn" %>
      <% end %>
      <%= link_to "Cancel", trips_path, class:"cancel_btn" %>

    </div>

app/views/trips/show.html.erb
<div class="trip_title">
  <div class="left_title"><%= @trip.title %></div>
  <div class="right_title">
    <%= form_tag @trip.travelings.new do %>
      <%= select_tag :user_id, options_from_collection_for_select(@users, "id", "nickname"), { class:"friends_input", id: "select-state", multiple: "multiple", tabindex:"-1", placeholder: "Add a friend..." } %>
      <%= hidden_field_tag :trip_id, @trip.id %>
      <%= submit_tag "+", class: 'add_user_button' %>
    <% end %>
  </div>
</div>
<script>
  $('#select-state').selectize({
    maxItems: 3
  });
</script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBbJVzlHZ4HApCCUHOunA1mB0kB5KA2f-E"></script>
<script type="text/javascript">

  function initialize() {
    var mapOptions = {
      center: { lat: 39.750742, lng: -105.000239 },
      zoom: 13
    };
    var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    var $posts = $('.post')
    var $filteredPosts = $posts.filter( function(index, post) {
      return $(this).data('lat') && $(this).data('lon');
    });

    var allMarkers = $filteredPosts.toArray().forEach(function(post) {
      var myLatlng = new google.maps.LatLng(post.dataset.lat, post.dataset.lon);
      new google.maps.Marker({
        position: myLatlng,
        map: map,
      });
    });
  }

  google.maps.event.addDomListener(window, 'load', initialize);
</script>
<div id="map-canvas" style="height: 400px; width: 100%; margin: 0; padding: 0;"></div>

<div class="push_5"></div>
<div class="friends_input_cleaner"></div>
<%= render "posts/posts_feed" %>