config/routes.rb
Rails.application.routes.draw do
  get 'hideposts/index'

  root to: 'welcome#home'

  get   'feed',                     to: 'posts#feed',       as: 'feed'
  get   '/login',                   to: 'sessions#bounce',  as: :login
  get   '/logout',                  to: 'sessions#destroy', as: :logout
  match '/auth/instagram/callback', to: 'sessions#create',  via: [:get]
  match '/auth/twitter/callback',   to: 'sessions#twitter', via: [:get]
  match '/auth/failure',            to: 'sessions#failure', via: [:get]

  resources :menu, only: [:index]
  resources :trips
  resources :travelings
  resources :hideposts
  resources :posts do
    resources :comments
  end

  get '/profile/:id', to: 'profiles#show', as: 'profile'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :posts, only: [:index, :show]
      resources :trips, only: [:index, :show] do
        resources :posts, only: [:index, :show]
      end
    end
  end

end

app/controllers/hideposts_controller.rb
class HidepostsController < ApplicationController
  def index
    @posts   = current_user.posts.where(hide: true).sort_by { |post| post.properties["created_date"]}
    @comment = Comment.new
  end

  def create
    Post.find(params[:id].to_i).update_attribute(:hide, true)
    redirect_to feed_path
  end

  def destroy
    Post.find(params[:id].to_i).update_attribute(:hide, false)
    redirect_to feed_path
  end

end

app/helpers/hideposts_helper.rb
module HidepostsHelper
end

app/views/hideposts/_instagram.html.erb
  <% if post.source == "Instagram" %>
    <div class="full_width">
      <%= image_tag post.user.image, class:"profile_picture" %>
      <div class="profile_nickname"><%= post.user.nickname %></div>
      <div class="date"><%= "#{wordy_time(post) unless post.created_date == nil} at #{post.properties["place_name"]}" %></div>
    </div>
      <%= form_tag(hidepost_path(post.id), method: :delete) do %>
        <%= hidden_field_tag "id", post.id %>
        <%= hidden_field_tag "method", "delete" %>
        <%= submit_tag 'Show your post' %>
      <% end %>
    <div class="text"><%= post.properties["caption"] %></div>
    <div class="post_image" style="background-image: url(<%= post.properties['url'] %> );"></div>
  <% end %>

app/views/hideposts/_posts_feed.html.erb
<% cache @posts do %>
    <div class="post">
      
      <%= render partial: "hideposts/instagram", collection: @posts, as: :post %>

      <%= render partial: "hideposts/twitter", collection: @posts, as: :post %>

    </div>
<% end %>

app/views/hideposts/_twitter.html.erb
<% if post.source == "Twitter" %>
  <div class="full_width">
    <%= image_tag post.user.image, class:"profile_picture" %>
    <div class="profile_nickname"><%= post.user.nickname %></div>
    <div class="date"><%= "#{wordy_time(post) unless post["caption"] == nil} at #{post.properties["place_name"]}" %></div>
  </div>
  <%= form_tag(hidepost_path(post.id), method: :delete) do %>
    <%= hidden_field_tag "id", post.id %>
    <%= hidden_field_tag "method", "delete" %>
    <%= submit_tag 'Show your post' %>
  <% end %>
  <div class="text"><%= post.properties["text"] %></div>
  <% if post.properties["image_url"] %>
    <div class="post_image" style="background-image: url(<%= post.properties['image_url'] %> );"></div>
  <% end %>
<% end %>

app/views/hideposts/index.html.erb
<div class="push_5"></div>
<%= render "hideposts/posts_feed" %>