config/routes.rb
Rails.application.routes.draw do
  get 'hideposts/index'

  root to: 'welcome#home'

  get   'feed',                     to: 'posts#feed',       as: 'feed'
  get   '/login',                   to: 'sessions#bounce',  as: :login
  get   '/logout',                  to: 'sessions#destroy', as: :logout
  match '/auth/instagram/callback', to: 'sessions#create',  via: [:get]
  match '/auth/twitter/callback',   to: 'sessions#twitter', via: [:get]
  match '/auth/failure',            to: 'sessions#failure', via: [:get]

  resources :menu, only: [:index]
  resources :trips
  resources :travelings
  resources :hideposts
  resources :posts do
    resources :comments
  end

  get '/profile/:id', to: 'profiles#show', as: 'profile'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :posts, only: [:index, :show]
      resources :trips, only: [:index, :show] do
        resources :posts, only: [:index, :show]
      end
    end
  end

end

app/views/shared/_flash_notices.html.erb
<% if flash.any? %>
  <div id="flash">
    <% flash.each do |key, value| %>
      <div id="flash_<%= key %>"><%= value %></div>
    <% end %>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<div class="navigation">
  <%= link_to trips_path do %>
    <div class="options_link left link_to">Your Trips</div>
  <% end %>

  <div class="text_divider left">|</div>

  <%= link_to feed_path do %>
    <div class="text left">Your Feed</div>
  <% end %>

  <div class="text_divider left">|</div>

  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li><%= link_to 'Add Twitter', "/auth/twitter" %></li>
    <li><%= link_to 'Hidden posts', hideposts_path %></li>
    <li><%= link_to 'Logout', logout_path %></li>
  </ul>

</div>
<div class="floater_4"></div>